export const outfitMeasurementMap: Record<number, any> = {
  1: {
    'Kurta Pajama (Top)': [
      'kurta_length',
      'shoulder',
      'upper_chest',
      'bust',
      'waist',
      'seat',
      'arm_hole',
      'sleeve_length',
      'sleeve_circumference',
      'front_neck_depth',
      'back_neck_depth',
    ],
    'Kurta Pajama (Bottom)': ['pyjama_length', 'pyjama_hip', 'knee', 'ankle'],
  },
  2: {
    Dress: [
      'length',
      'shoulder',
      'upper_chest',
      'bust',
      'waist',
      'seat',
      'arm_hole',
      'sleeve_length',
      'bicep',
      'elbow_round',
      'sleeve_circumference',
      'front_neck_depth',
      'back_neck_depth',
      'cross_front',
      'cross_back',
      'dart_point',
    ],
  },
  3: {
    'Saree Blouse': [
      'blouse_length',
      'bust',
      'upper_chest',
      'below_bust',
      'shoulder',
      'arm_hole',
      'sleeve_length',
      'sleeve_circumference',
      'bicep',
      'elbow_round',
      'apex_to_apex_length',
      'shoulder_to_apex_length',
      'front_neck_depth',
      'back_neck_depth',
      'cross_front',
      'cross_back',
      'dart_point',
    ],
    measurement_key_list: [
      'blouse_length',
      'bust',
      'upper_chest',
      'below_bust',
      'shoulder',
      'arm_hole',
      'sleeve_length',
      'sleeve_circumference',
      'bicep',
      'elbow_round',
      'apex_to_apex_length',
      'shoulder_to_apex_length',
      'front_neck_depth',
      'back_neck_depth',
      'cross_front',
      'cross_back',
      'dart_point',
    ],
  },
  4: {
    "Men's Suit (Top)": [
      'shirt_length',
      'neck',
      'shoulder',
      'chest',
      'waist',
      'seat',
      'sleeve_length',
      'sleeve_circumference',
    ],
    "Men's Suit (Bottom)": ['bottom_waist', 'bottom_seat', 'calf', 'bottom', 'pant_length', 'fly'],
  },
  5: {
    Pants: [
      'bottom_waist',
      'bottom_seat',
      'thigh',
      'calf',
      'bottom',
      'pant_length',
      'fly',
      'in_seam',
      'crotch',
    ],
  },
  6: {
    'Night Gown': [
      'gown_length',
      'shoulder',
      'upper_chest',
      'bust',
      'waist',
      'seat',
      'arm_hole',
      'sleeve_length',
      'sleeve_circumference',
      'front_neck_depth',
      'back_neck_depth',
    ],
  },
  7: {
    'Ladies Suit (Top)': [
      'kameez_length',
      'upper_chest',
      'bust',
      'below_bust',
      'waist',
      'hip_circum',
      'shoulder',
      'arm_hole',
      'bicep',
      'sleeve_length',
      'sleeve_circumference',
      'cross_front',
      'cross_back',
      'front_neck_depth',
      'back_neck_depth',
    ],
    'Ladies Suit (Bottom)': [
      'salwar_length',
      'bottom_waist',
      'thigh',
      'knee',
      'calf',
      'mohri',
      'crotch',
    ],
  },
  8: {
    Shirt: [
      'shirt_length',
      'neck',
      'shoulder',
      'chest',
      'waist',
      'seat',
      'sleeve_length',
      'bicep',
      'elbow_round',
      'sleeve_circumference',
      'arm_hole',
    ],
  },
  9: {
    'Under Skirt': ['waist', 'length'],
  },
  10: {
    'Nehru Jacket': ['length', 'neck', 'chest', 'waist'],
  },
  11: {
    Pardi: ['above_head', 'pardi_shoulder', 'around_shoulder', 'pardi_length', 'pardi_gher', 'kas'],
    Lenga: ['lenga_shoulder', 'bust', 'waist', 'hip', 'lenga_length', 'lenga_gher'],
  },
  12: {
    'Waist Coat': ['length', 'chest', 'waist'],
  },
  13: {
    Lehenga: ['waist_circum', 'hip_circum', 'waist_to_knee', 'length'],
  },
  14: {
    'Sharara (Top)': [
      'length',
      'upper_chest',
      'bust',
      'below_bust',
      'waist',
      'hip_circum',
      'shoulder',
      'arm_hole',
      'bicep',
      'sleeve_length',
      'sleeve_circumference',
      'cross_front',
      'cross_back',
      'front_neck_depth',
      'back_neck_depth',
    ],
    'Sharara (Bottom)': [
      'salwar_length',
      'bottom_waist',
      'thigh',
      'knee',
      'calf',
      'mohri',
      'crotch',
      'nikker_length',
      'sharara_circum',
    ],
  },
  15: {
    'Sherwani (Top)': [
      'shirt_length',
      'neck',
      'shoulder',
      'chest',
      'waist',
      'hip_circum',
      'sleeve_length',
      'bicep',
      'elbow_round',
      'sleeve_circumference',
      'arm_hole',
    ],
    'Sherwani (Bottom)': [
      'bottom_waist',
      'bottom_hip_circum',
      'thigh',
      'calf',
      'bottom',
      'bottom_length',
      'fly',
      'in_seam',
      'crotch',
    ],
  },
  16: {
    'Indo Western (Top)': [
      'shirt_length',
      'neck',
      'shoulder',
      'chest',
      'waist',
      'hip_circum',
      'sleeve_length',
      'bicep',
      'elbow_round',
      'sleeve_circumference',
      'arm_hole',
    ],
    'Indo Western (Bottom)': [
      'bottom_waist',
      'bottom_hip_circum',
      'thigh',
      'calf',
      'bottom',
      'bottom_length',
      'fly',
      'in_seam',
      'crotch',
    ],
  },
};
